info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /api/appelsACandidatures/:
    get:
      operationId: appelsACandidatures_list
      tags:
      - appelsACandidatures
    post:
      operationId: appelsACandidatures_create
      tags:
      - appelsACandidatures
  /api/appelsACandidatures/{id}/:
    get:
      operationId: appelsACandidatures_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - appelsACandidatures
  /api/demandes/:
    get:
      operationId: demandes_list
      tags:
      - demandes
    post:
      operationId: demandes_create
      tags:
      - demandes
  /api/demandes/{id}/:
    delete:
      operationId: demandes_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - demandes
    get:
      operationId: demandes_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - demandes
    put:
      operationId: demandes_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - demandes
  /api/institutions/:
    get:
      operationId: institutions_list
      tags:
      - institutions
    post:
      operationId: institutions_create
      tags:
      - institutions
  /api/institutions/{id}/:
    delete:
      operationId: institutions_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - institutions
    get:
      operationId: institutions_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - institutions
    put:
      operationId: institutions_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - institutions
  /api/offres/:
    get:
      operationId: offres_list
      tags:
      - offres
    post:
      operationId: offres_create
      tags:
      - offres
  /api/offres/{id}/:
    delete:
      operationId: offres_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - offres
    get:
      operationId: offres_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - offres
  /api/sousDemandes/{id}/:
    get:
      operationId: sousDemandes_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - sousDemandes
  /api/urlsFilesDemandesInst/:
    get:
      operationId: urlsFilesDemandesInst_list
      tags:
      - urlsFilesDemandesInst
    post:
      operationId: urlsFilesDemandesInst_create
      tags:
      - urlsFilesDemandesInst
servers:
- url: ''
