# Generated by Django 3.1.13 on 2021-11-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('alias', models.CharField(max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnneeScolaireUser',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveBigIntegerField()),
                ('annee_id', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'AnneeUser',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dept', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddConstraint(
            model_name='anneescolaireuser',
            constraint=models.UniqueConstraint(fields=('user_id', 'annee_id'), name='user_annee_unique'),
        ),
    ]
